### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by huseyinkarael** [juanmicl/igcreator#1]
error picture
![evve](https://user-images.githubusercontent.com/39264365/46257094-b555e080-c4bc-11e8-965e-c290cbbc420c.png)

**Comment by juanmicl** [comment]
The error seems to be at /examples/register.php -> `include __DIR__ . "/../vendor/autoload.php";`

1. Did you follow [installation](https://github.com/juanmicl/igcreator#installation) on readme?
2. I think you can't find autoload.php because you are executing inside vendor folder. 

You have to create a "public" directory like this:
![public](https://i.imgur.com/r5cZYnV.png)
and put inside register.php . Then you can execute at www/by/public/register.php

**Comment by juanmicl** [comment]
yes, you can. I recommend XAMPP on Windows and Nginx + php + mysql on linux

**Comment by huseyinkarael** [comment]
Is there proxy support?

**Comment by juanmicl** [comment]
I will add soon

**Comment by huseyinkarael** [comment]
{"igcreator":{"created":null,"username":"vbctygcgdh","password":"dfsdfsdds123","email":"bdvdbdgt2@gmail.com","firstname":"YourName"},"instagram":null}  

İt error?

**Comment by juanmicl** [comment]
Please, enable showing php errors to see. First check if you have php curl installed

**Comment by huseyinkarael** [comment]
php curl was set up but it still did not work.

**Comment by juanmicl** [comment]
Put this at the begining of register.php  
```
ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);
```
And show me the output :+1:

**Comment by huseyinkarael** [comment]
again the same output .

**Comment by juanmicl** [comment]
Try to enable php errors vía php.ini file (enable all errors)  and show me the output.  We need to know why curl response is null

**Comment by juanmicl** [comment]
I know but send me any php logs or something

**Comment by huseyinkarael** [comment]
I don't know how to do that.

**Comment by huseyinkarael** [comment]
Fatal error: Call to undefined function juanmicl\igcreator\curl_init() in C:\AppServ\www\by\vendor\juanmicl\igcreator\src\create.php on line 9

**Comment by huseyinkarael** [comment]
http://prntscr.com/l0x8u4

php.ini

**Comment by juanmicl** [comment]
That means you don't have CURL support on php, you have to enable it.

Go to your php.ini file and remove the ; mark from the beginning of the following line:

`;extension=php_curl.dll`
After you have saved the file you must restart your HTTP server software (e.g. Apache) before this can take effect.

**Comment by huseyinkarael** [comment]
is it correct?
http://prntscr.com/l0xjnl

**Comment by juanmicl** [comment]
yes, did you saved an restarted your server?

try to install [XAMPP](https://www.apachefriends.org/xampp-files/7.2.10/xampp-win32-7.2.10-0-VC15-installer.exe) this includes CURL and PHP

**Comment by juanmicl** [comment]
Any updates about your issue?

**Comment by huseyinkarael** [comment]
my problem continues

**Comment by juanmicl** [comment]
Did you installed XAMPP and tested there?

**Comment by huseyinkarael** [comment]
new error :
{"igcreator":{"created":false,"username":"whiteduck282","password":"l15rvofudv","email":"whiteduck282@emaildomain.com","firstname":"justus anton"},"instagram":{"account_created":false,"errors":{"ip":["The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http:\/\/help.instagram.com\/"]},"status":"ok","error_type":"signup_block"}}

**Comment by huseyinkarael** [comment]
corrected the problem, but where are the newly opened accounts registered?

**Comment by juanmicl** [comment]
> corrected the problem, but where are the newly opened accounts registered?

you have the details on "igcreator" array output. If you mean where they are saved, for now we are not saving anywhere.

**Comment by huseyinkarael** [comment]
how do I access the created accounts?
for example: username: password

**Comment by huseyinkarael** [comment]
How do I get the csrf token?

**Comment by juanmicl** [comment]
For now we don't provide any csrftoken because it changes every time you login at Instagram. 

We only register accounts on Instagram. I think you will need to extract csrf token by login yourself :)

**Comment by huseyinkarael** [comment]
Will you add new features?

**Comment by juanmicl** [comment]
Tell me wich new features do you want and I will add they if I can :+1:

**Comment by huseyinkarael** [comment]
proxy
save created accounts (for example: username: pass)
Add a profile picture
cookie extraction (eg;` 

`# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.instagram.com	TRUE	/	FALSE	1489247428	sessionid	
www.instagram.com	FALSE	/	FALSE	2119967428	mid	WMQcxAAEAAEoHJhK3n3rqOzxOwMf
www.instagram.com	FALSE	/	TRUE	1520697037	csrftoken	YccBZ8DotKaZheBjCJMei7aSiTcCd7NY
www.instagram.com	FALSE	/	FALSE	1497023437	ds_user_id	1497352634
www.instagram.com	FALSE	/	FALSE	1489247437	target	""
#HttpOnly_www.instagram.com	FALSE	/	TRUE	1497023437	sessionid	IGSC036e61cf60b7e6adcaf22ce980c8fac5a6127ac559561453b677d1663f402ee5%3A5FzHoNSt2pPOYShwyf9tzZyluxgb8aBG%3A%7B%22_auth_user_hash%22%3A%22%22%2C%22_auth_user_id%22%3A1497352634%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_platform%22%3A4%2C%22_token_ver%22%3A2%2C%22_token%22%3A%221497352634%3AKhQAFnz1KvP1i2aPOPUYIMAiHy6ZknCP%3A552d95e522008f18ac0b82c4a9f1cb9d4e8430ad17f459cb7c3ad74aeeb2cdee%22%2C%22last_*******ed%22%3A1489247436.9248548%7D`

)

**Comment by huseyinkarael** [comment]
I just need this

cookie extraction (eg;`

#HttpOnly_.instagram.com	TRUE	/	FALSE	1489247428	sessionid
www.instagram.com	FALSE	/	FALSE	2119967428	mid	WMQcxAAEAAEoHJhK3n3rqOzxOwMf
www.instagram.com	FALSE	/	TRUE	1520697037	csrftoken	YccBZ8DotKaZheBjCJMei7aSiTcCd7NY
www.instagram.com	FALSE	/	FALSE	1497023437	ds_user_id	1497352634
www.instagram.com	FALSE	/	FALSE	1489247437	target	""
#HttpOnly_www.instagram.com	FALSE	/	TRUE	1497023437	sessionid IGSC036e61cf60b7e6adcaf22ce980c8fac5a6127ac559561453b677d1663f402ee5%3A5FzHoNSt2pPOYShwyf9tzZyluxgb8aBG%3A%7B%22_auth_user_hash%22%3A%22%22%2C%22_auth_user_id%22%3A1497352634%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_platform%22%3A4%2C%22_token_ver%22%3A2%2C%22_token%22%3A%221497352634%3AKhQAFnz1KvP1i2aPOPUYIMAiHy6ZknCP%3A552d95e522008f18ac0b82c4a9f1cb9d4e8430ad17f459cb7c3ad74aeeb2cdee%22%2C%22last_*******ed%22%3A1489247436.9248548%7D`

**Comment by huseyinkarael** [comment]
{"devicestring":"23\/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890","uuid":"548f66a0-e548-42da-afad-7c6bc23747fb","adid":"3f08c7d0-8fa8-4087-a075-26c469063177","phone_id":"82fc446b-0743-4e01-9052-f67c4ebce18d","device_id":"android-e049be31aba225a9","ip":"45.247.214.82","username_id":3421574624,"asns5a2cf36d6e6e6a2acda59399649981a4":341,"token":"W9VnhnQYRkpawsQJTH5MB2NjKDVCznxH","cookie":"csrftoken=W9VnhnQYRkpawsQJTH5MB2NjKDVCznxH;rur=PRN;mid=Wi9zUQABAAGb9JKhu6HGWe8OAhZC;urlgen=%22%7B%5C%22time%5C%22%3A+1514497151%5C054+%5C%222a01%3A4f8%3A202%3A33e7%3Ad7aa%3A9d31%3A16cc%3A2e9b%5C%22%3A+24940%7D%3A1eUftP%3AyYt5YFUbVNuFOwOrMiE1ok-pR-k%22;ds_user=marcloemda;ds_user_id=3421574624;sessionid=3421574624%3AfQtZldETRJs3Wz%3A22","last_login":1513059207,"last_experiments":1513059207}

**Comment by juanmicl** [comment]
> Example:
> {"devicestring":"23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890","uuid":"548f66a0-e548-42da-afad-7c6bc23747fb","adid":"3f08c7d0-8fa8-4087-a075-26c469063177","phone_id":"82fc446b-0743-4e01-9052-f67c4ebce18d","device_id":"android-e049be31aba225a9","ip":"45.247.214.82","username_id":3421574624,"asns5a2cf36d6e6e6a2acda59399649981a4":341,"token":"W9VnhnQYRkpawsQJTH5MB2NjKDVCznxH","cookie":"csrftoken=W9VnhnQYRkpawsQJTH5MB2NjKDVCznxH;rur=PRN;mid=Wi9zUQABAAGb9JKhu6HGWe8OAhZC;urlgen=%22%7B%5C%22time%5C%22%3A+1514497151%5C054+%5C%222a01%3A4f8%3A202%3A33e7%3Ad7aa%3A9d31%3A16cc%3A2e9b%5C%22%3A+24940%7D%3A1eUftP%3AyYt5YFUbVNuFOwOrMiE1ok-pR-k%22;ds_user=marcloemda;ds_user_id=3421574624;sessionid=3421574624%3AfQtZldETRJs3Wz%3A22","last_login":1513059207,"last_experiments":1513059207}

please open a new issue to new functions :+1:

**Comment by huseyinkarael** [comment]
Ok
