### ISSUE TITLE
can I take the cookie out this way?

### ISSUE THREAD

**Issue by huseyinkarael** [juanmicl/igcreator#2]
can I take the cookie out this way?

{"username_id":"2295375843","token":"dAFHJEtw1aKo92auKRdmOPUPq8NWgbk1","cookie":"sessionid=2295375843%3AaDEiduuJnoJHRB%3A29;csrftoken=dAFHJEtw1aKo92auKRdmOPUPq8NWgbk1;mid=WYyP8AABAAGNxT9DTP1mxx_wKCiw;ds_user_id=2295375843;ds_user=jdremre_ada7;rur=FRC;urlgen=%22%7B%5C%22time%5C%22%3A+1516092253%5C054+%5C%222a01%3A4f8%3A202%3A33e7%3A23a2%3Abe1a%3Acfc2%3A2bf%5C%22%3A+24940%7D%3A1ebMqr%3ABFi9NSkYGYVD6urnv-gqNCOBEdw%22","devicestring":"18\/4.3; 320dpi; 720x1280; ZTE; N8010_APT; N8010_APT; qcom","uuid":"d41b709b-8cfd-4801-b8d6-d815b9557c74","adid":"bc9973c8-e6de-4a4f-bd99-d208622d08de","phone_id":"434cbc9b-9183-4ba2-b205-8bf14955c96a","device_id":"android-1612babc24401d14","ip":"78.179.191.25","asnsb8bf5f539f8b4a6392f1ec6d012d8aa8":602,"asns5a2cf36d6e6e6a2acda59399649981a4":954,"asns8a2d87fd699b800545fd739e9972ebe5":627}

**Comment by juanmicl** [comment]
I'm going to try :)

**Comment by huseyinkarael** [comment]
Thank you good man,
Create this file for created accounts.

**Comment by huseyinkarael** [comment]
@juanmicl Is it possible to do it?

**Comment by juanmicl** [comment]
I think so, tomorrow I will Try :smiley:

**Comment by huseyinkarael** [comment]
I'm gonna die out of curiosity.

**Comment by huseyinkarael** [comment]
> I think so, tomorrow I will Try

hello, how is the situation?

**Comment by juanmicl** [comment]
https://github.com/juanmicl/igcreator/projects/1

**Comment by juanmicl** [comment]
I can output on a json this data:
- userID
- csrftoken
- sessionid(cookie)

are you agree @huseyinkarael ?

**Comment by huseyinkarael** [comment]
Yes, but can I take it as in this example?

{
    "devicestring": "24\/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom",
    "uuid": "7340546f-6a90-4bee-8997-a323fb9d0227",
    "adid": "627170df-2e4f-45b0-a0e2-bebff999cb4f",
    "phone_id": "f069ce58-51fb-4559-90dc-d3aab6848b17",
    "device_id": "android-ac806678e4fbf802",
    "ip": "92.45.120.105",
    "username_id": 1370123051,
    "asns5a2cf36d6e6e6a2acda59399649981a4": 2044,
    "token": "JQ0FbTN1krNU9sLr3m75NLB83g0imkSo",
    "cookie": "csrftoken=JQ0FbTN1krNU9sLr3m75NLB83g0imkSo;rur=ASH;mid=WlX2vAABAAFKxKiRpFsQ5OIfegrm;ds_user=yemekkmekanlarii;ds_user_id=1370123051;urlgen=%22%7B%5C%22time%5C%22%3A+1516068076%5C054+%5C%222a01%3A4f8%3A202%3A33e7%3A9667%3A7013%3A482d%3A592f%5C%22%3A+24940%7D%3A1ebGYu%3AolwN6QCp0at4D9IZJTx4kJT0Nc8%22;sessionid=IGSC8cf5cf9469e1b13c3891bdb313fdb003dff4ce36f68add66f4422ed3b3aac6ed%3APJK44MTQTbeFHT5H3yZAcZTWnwH4qLVN%3A%7B%22_auth_user_id%22%3A1370123051%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_token%22%3A%221370123051%3AueQB0GjT934SfkUaxkDsvcgPDMNNiusY%3Aac5fcf8de1da5b56035aaa2f75af224250ace500e51112ce8fab9b59daa7fd56%22%2C%22_platform%22%3A1%2C%22_remote_ip%22%3A%22185.106.23.93%22%2C%22_mid%22%3A%22WlX2vAABAAFKxKiRpFsQ5OIfegrm%22%2C%22_user_agent_md5%22%3A%2266956866d8ee40803452c1d74f8ce927%22%2C%22_token_ver%22%3A2%2C%22last_refreshed%22%3A1516975821.8391606808%7D",
    "last_login": 1515583166,
    "last_experiments": 1515583166
}

**Comment by huseyinkarael** [comment]
or can you do that?

` Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.instagram.com	TRUE	/	FALSE	1489247428	sessionid	
www.instagram.com	FALSE	/	FALSE	2119967428	mid	WMQcxAAEAAEoHJhK3n3rqOzxOwMf
www.instagram.com	FALSE	/	TRUE	1520697037	csrftoken	YccBZ8DotKaZheBjCJMei7aSiTcCd7NY
www.instagram.com	FALSE	/	FALSE	1497023437	ds_user_id	1497352634
www.instagram.com	FALSE	/	FALSE	1489247437	target	""
#HttpOnly_www.instagram.com	FALSE	/	TRUE	1497023437	sessionid	IGSC036e61cf60b7e6adcaf22ce980c8fac5a6127ac559561453b677d1663f402ee5%3A5FzHoNSt2pPOYShwyf9tzZyluxgb8aBG%3A%7B%22_auth_user_hash%22%3A%22%22%2C%22_auth_user_id%22%3A1497352634%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_platform%22%3A4%2C%22_token_ver%22%3A2%2C%22_token%22%3A%221497352634%3AKhQAFnz1KvP1i2aPOPUYIMAiHy6ZknCP%3A552d95e522008f18ac0b82c4a9f1cb9d4e8430ad17f459cb7c3ad74aeeb2cdee%22%2C%22last_*******ed%22%3A1489247436.9248548%7D`

**Comment by juanmicl** [comment]
> or can you do that?
> 
> ` Netscape HTTP Cookie File
> 
> # http://curl.haxx.se/docs/http-cookies.html
> # This file was generated by libcurl! Edit at your own risk.
> #HttpOnly_.instagram.com	TRUE	/	FALSE	1489247428	sessionid
> [www.instagram.com](http://www.instagram.com)	FALSE	/	FALSE	2119967428	mid	WMQcxAAEAAEoHJhK3n3rqOzxOwMf
> [www.instagram.com](http://www.instagram.com)	FALSE	/	TRUE	1520697037	csrftoken	YccBZ8DotKaZheBjCJMei7aSiTcCd7NY
> [www.instagram.com](http://www.instagram.com)	FALSE	/	FALSE	1497023437	ds_user_id	1497352634
> [www.instagram.com](http://www.instagram.com)	FALSE	/	FALSE	1489247437	target	""
> #HttpOnly_[www.instagram.com](http://www.instagram.com)	FALSE	/	TRUE	1497023437	sessionid	IGSC036e61cf60b7e6adcaf22ce980c8fac5a6127ac559561453b677d1663f402ee5%3A5FzHoNSt2pPOYShwyf9tzZyluxgb8aBG%3A%7B%22_auth_user_hash%22%3A%22%22%2C%22_auth_user_id%22%3A1497352634%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_platform%22%3A4%2C%22_token_ver%22%3A2%2C%22_token%22%3A%221497352634%3AKhQAFnz1KvP1i2aPOPUYIMAiHy6ZknCP%3A552d95e522008f18ac0b82c4a9f1cb9d4e8430ad17f459cb7c3ad74aeeb2cdee%22%2C%22last_*******ed%22%3A1489247436.9248548%7D`

I can output this but I can't get any "device_id" or "phone_id"

**Comment by huseyinkarael** [comment]
not a problem this is enough for me.

**Comment by juanmicl** [comment]
> phone_id

Ahhhh okay, I understand now... I can generate phone_id and device_id randomly

**Comment by huseyinkarael** [comment]
> > phone_id
> 
> Ahhhh okay, I understand now... I can generate phone_id and device_id randomly

It's a great idea

**Comment by juanmicl** [comment]
Implemented :+1:
