### ISSUE TITLE
token real?

### ISSUE THREAD

**Issue by huseyinkarael** [juanmicl/igcreator#4]
Is csrf token real?

**Comment by juanmicl** [comment]
Yes, csrftoken is real on getCookies :smile:

**Comment by huseyinkarael** [comment]
That's not what I want.   :(

**Comment by juanmicl** [comment]
I Put all the cookies inside json, didn't change nothing. Like you said.

**Comment by juanmicl** [comment]
Then, What do you want to do?

**Comment by huseyinkarael** [comment]
I don't know php, and I want to tell you this.
I want the cookie information to be saved in the folder when the account is successfully created.
Sample
the username.jso
I wish this was on Json.
![image](https://user-images.githubusercontent.com/39264365/46546346-6c919380-c8d1-11e8-9cfd-a84d334252c2.png)

**Comment by juanmicl** [comment]
Okay will do it, and save "username.txt".

**Comment by huseyinkarael** [comment]
Cookies take a long time to get very complicated editing.

**Comment by huseyinkarael** [comment]
Why isn't it exporting like in the picture?

**Comment by huseyinkarael** [comment]
> > Why isn't it exporting like in the picture?
> 
> Now with this [example](https://github.com/juanmicl/igcreator/blob/master/examples/getCookiesToFile.php) you can export like you want

![image](https://user-images.githubusercontent.com/39264365/46607304-34749580-cb09-11e8-8ef2-f872185f76e9.png)
Why are some values empty?

**Comment by juanmicl** [comment]
don't care about that, worked for me login without credentials and only cookie.txt file

**Comment by huseyinkarael** [comment]
do I get an automatic cookie if an account is created?

**Comment by juanmicl** [comment]
No, you need to do yourself. I mean register and login (you can do it on a simple php script).
