### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by huseyinkarael** [juanmicl/igcreator#5]
error picture:
![image](https://user-images.githubusercontent.com/39264365/46608052-06dd1b80-cb0c-11e8-9188-fd473e0d5327.png)

**Comment by juanmicl** [comment]
"Too few arguments" mean you are missing username, password, firstname.... using **register()** 
if you want random use **register_rand()**

**Comment by juanmicl** [comment]
Example code were wrong. Fixed now :+1:
