### ISSUE TITLE
where to put require autoload.php

### ISSUE THREAD

**Issue by Itwww** [juanmicl/igcreator#8]
i did it just like u said i did php /bin/composer.phar require juanmicl/igcreator
it went all right but now i have no idea where to put the require _DIR_.'/../vendor/autoload.php';
$create = new \juanmicl\igcreator\create();

Thank you for your help<3

**Comment by juanmicl** [comment]
Hi @Itwww ,

You have to look this:
- Find where is located your "autoload.php" file to call it.
- Where do you want to execute your code.

As you can see at [examples](https://github.com/juanmicl/igcreator/blob/master/examples/) folder, you need to require autoload.php usually located at `/vendor/autoload.php` If you want to make a `public` folder and yourscript.php inside you must `require __DIR__.'/../vendor/autoload.php';`

Conclusion, search information about require php if you don't know what are you doing. Or you can just copy [examples](https://github.com/juanmicl/igcreator/blob/master/examples/) folder inside your project folder and should work :+1:

**Comment by Itwww** [comment]
and is there any output on the website or something? I go on the site and see only a blank site

**Comment by juanmicl** [comment]
Yes, it sould print a json response.

[Enable php errors](http://bfy.tw/KOwC) and show me here to help you :)

**Comment by Itwww** [comment]
thank you for your help <3 Asap as iam home i will let u know if i ger errors

**Comment by Itwww** [comment]
I get the error: 
Fatal error: Call to undefined function juanmicl\igcreator\curl_init() in /var/www/html/insta/vendor/juanmicl/igcreator/src/create.php on line 9

**Comment by juanmicl** [comment]
you need to [install php curl](http://lmgtfy.com/?q=how+to+install+php+curl) and it should work :)

you can install xampp (that comes with curl enabled).

**Comment by Itwww** [comment]
one last question. why do i get this error and is there any fix?
{"igcreator":{"created":false,"username":"sadbird935","password":"y3mysjanq6","email":"sadbird935@emaildomain.com","firstname":"kaya da\u011flaro\u011flu"},"instagram":{"account_created":false,"errors":{"ip":["The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http:\/\/help.instagram.com\/"]},"status":"ok","error_type":"signup_block"}}

**Comment by juanmicl** [comment]
See: "The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http://help.instagram.com/"

You need to use another proxy or ip address

**Comment by Itwww** [comment]
and the register_randomproxysupport doesnt work?

**Comment by juanmicl** [comment]
`include __DIR__ . "/../vendor/autoload.php";
$create = new \juanmicl\igcreator\createProxy();
**$create->register_rand('43587gv3b4.com', 'proxy:port');**
`

**Comment by Itwww** [comment]
ahh thank you for ur support <3

**Comment by Itwww** [comment]
will there be added proxy lists in ur script?
