### ISSUE TITLE
created: false, username: null

### ISSUE THREAD

**Issue by UHaweq12** [juanmicl/igcreator#9]
I only get the response: {"igcreator":{"created":"false","username":null,"password":null,""firstname":" "},"instagram":"no response"}

**Comment by UHaweq12** [comment]
There arent any errors showing up. 
I only get the json response: {"igcreator":{"created":"false","username":null,"password":null,"email":"@mydomain.de","firstname":" "},"instagram":"no response"}

**Comment by juanmicl** [comment]
Tell me:
- Opertaing System
- Xampp, nginx, other?
- ALL errors enabled?
- CURL enabled and tested?
- phpinfo output

**Comment by UHaweq12** [comment]
system debian 8
apache2
yes
yes
only the output i posted
my code = ur example code with my domain.

**Comment by Itwww** [comment]
any idea?

**Comment by UHaweq12** [comment]
any idea whats going on?

**Comment by juanmicl** [comment]
I did a few changes on the code updating namegenerator API changes try to update and run the example.

`composer require juanmicl/igcreator dev-master`

**Comment by juanmicl** [comment]
Any updates about this issue?

**Comment by UHaweq12** [comment]
still: {"igcreator":{"created":"false","username":null,"password":null,"email":"@Jaeger33211.de","firstname":" "},"instagram":"no response"}

**Comment by juanmicl** [comment]
Can you show here [your php logs](http://bfy.tw/KPKb) please?

**Comment by UHaweq12** [comment]
absolutely nothing in /var/logs/apache2/error.log

**Comment by juanmicl** [comment]
and /var/logs/php/...?

**Comment by juanmicl** [comment]
What PHP version are you using?

**Comment by UHaweq12** [comment]
php7,0 and i checked the php logs before

**Comment by juanmicl** [comment]
Doing this, you can know where php log is located. please check error log and if the file it's empty try to set error reporting to ALL on your php.ini
```
<?php
phpinfo();
```
You can make a curl request to namegenerator api to see what's going on:

```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://randomuser.me/api/?nat=GB&password=number,lower,10",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "Cache-Control: no-cache"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

**Comment by UHaweq12** [comment]
PHP Version 5.6.38-0+deb8u1
uff

**Comment by juanmicl** [comment]
try the curl request I posted above and post results

**Comment by juanmicl** [comment]
any updates about this issue?

**Comment by UHaweq12** [comment]
Response: {"results":[{"gender":"female","name":{"title":"ms","first":"susan","last":"warren"},"location":{"street":"4216 broadway","city":"southampton","state":"hampshire","postcode":"J3 8ES","coordinates":{"latitude":"76.6981","longitude":"69.1535"},"timezone":{"offset":"-6:00","description":"Central Time (US & Canada), Mexico City"}},"email":"susan.warren@example.com","login":{"uuid":"eec360c7-0cda-45e4-beff-d4f42e3cea45","username":"redfish394","password":"zu9z95x8sx","salt":"XZOu5tB7","md5":"ca14624f2b9b976e113e884c4d77f3b5","sha1":"d13e27e10bea93590549060d7d59ff8b81e09a1e","sha256":"83fbc521f2afb4a6783df01c30bfcba0f0e0fbeb68faa341055f2802d5d7d3d5"},"dob":{"date":"1992-03-02T07:17:16Z","age":26},"registered":{"date":"2005-10-07T05:09:59Z","age":13},"phone":"016973 74874","cell":"0750-506-573","id":{"name":"NINO","value":"HA 26 21 77 G"},"picture":{"large":"https://randomuser.me/api/portraits/women/65.jpg","medium":"https://randomuser.me/api/portraits/med/women/65.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/65.jpg"},"nat":"GB"}],"info":{"seed":"00f9a593694a09f9","results":1,"page":1,"version":"1.2"}}

**Comment by UHaweq12** [comment]
but still get null return
